### ISSUE TITLE
`is_expr()` is deprecated as of rlang 0.2.0.

### ISSUE THREAD

**Issue by dirkschumacher** [egnha/nofrills#52]
I get an `rlang` deprecation notice here.
``` r
library(nofrills)
fn(x, y = 1 ~ x + y)
#> Warning: `is_expr()` is deprecated as of rlang 0.2.0.
#> Please use `is_expression()` instead.
#> This warning is displayed once per session.
#> function (x, y = 1) 
#> x + y
```

<sup>Created on 2019-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by egnha** [comment]
Thanks for pointing this out. I’ll investigate ... (By the way, have you seen a similar warning with `gestalt::fn()`?)

**Comment by dirkschumacher** [comment]
`gestalt::fn()` works without warnings
